apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 for "user"
  postgres-user: dXNlcg==
  # Base64 for "password"
  postgres-password: cGFzc3dvcmQ=
  # Base64 for "postgresql+psycopg2://user:password@postgres:5432/airflow_db"
  airflow-db-conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9haXJmbG93X2Ri